name: Combine action-autotag with additional-tags-action

on:
  push:
    branches:
      - main

jobs:
  tag-action:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: valitydev/action-autotag@v1
  write-version:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Write Version to File
    steps:
    - uses: actions/checkout@master
    - name: Update version
      uses: brettdorrans/write-version-to-file@master
      with:
        filename: '/.VERSION'
        placeholder: '${VERSION}'
