name: Combine action-autotag with additional-tags-action

on:
  push:
    branches:
      - main

jobs:
  tag-action:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: valitydev/action-autotag@v1
